apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::255945442255:role/ce7-ty-eks-node-group-nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-27T08:04:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "851"
  uid: e83573d8-601a-4459-b7d7-64450ecaeecd
