apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::255945442255:role/ce7-ty-eks-node-group-nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::255945442255:user/lcchua7
      username: lcchua7
      groups:
        - system:masters
    - userarn: arn:aws:iam::255945442255:user/stphntn
      username: stphntn
      groups:
        - system:masters
    - userarn: arn:aws:iam::255945442255:user/junjie24
      username: junjie24
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-28T14:39:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3082"
  uid: 3572eb9e-ff52-4906-bf5e-926d1c5e229e
