name: PRI-ECR image pull config

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]
  push:
    branches: 
      - dev
    paths:
      - .github/workflows/private-ecr-img-pull-config.yaml
  # workflow_run:
  #   workflows: ["K8s helm installation"]
  #   types:
  #     - completed

jobs:
  AWS-private-ecr-image-pull-configuration:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      status: ${{ job.status }}
    defaults:
      run:
        working-directory: k8s/templates

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.EKS_REGION }}

    - name: Get kubernetes context
      run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_NAME }} --region ${{ vars.EKS_REGION }}

    - name: Authenticate and get docker config
      run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_PRI_REPO_URI }}
#          cat ~/.docker/config.json
#          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin XXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com

    - name: Create secret object in kubernetes
      run: |
          kubectl create secret generic docker-secret --from-file=.dockerconfigjson=/home/runner/.docker/config.json --type=kubernetes.io/dockerconfigjson -n default

  Summary:
    needs: [AWS-private-ecr-image-pull-configuration]
    runs-on: ubuntu-latest
    steps:
        - name: Adding markdown
          run: |
            INFO1=${{ needs.AWS-private-ecr-image-pull-configuration.status }}

            echo '##  Preparing Build Summary ' >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY

            echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
            echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
            echo "| Terraform-Checks  | $INFO1 |" >> $GITHUB_STEP_SUMMARY
            echo '' >> $GITHUB_STEP_SUMMARY

            echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY